### ISSUE TITLE
Markdown mode - &#32; appears instead of space in code block

### ISSUE THREAD

**Issue by AGBrown** [Neftas/supplementary-buttons-anki#63] opened 2016-01-13 17:39 UTC
If I enter the following into a card's field <sup>†</sup>

<pre>blah

```
def x[R](f: => R)
```
 </pre>

then when I click the markdown button, it gets turned into the expected formatted code, with the exception of the `(f: => R)` section which looks like the image at the bottom. That image is the same as the card when it is then viewed in preview mode.

If I remove markdown mode it then asks me to Cancel/Replace/Overwrite. Selecting Replace gives me the markdown <sup>‡</sup>:

<pre>blah

```
def x[R](f:&amp;#32;=>&amp;#32;R)
```
</pre>

<sup>†</sup>  _the `pre` tags in this comment's markdown are at the exact start and end of the text I enter to get this behaviour_
<sup>‡</sup> _I had to double encode the `&` part of the `&#32;` in the markdown behind this pre block, but it looks correct when rendered_

Image:

![image](https://cloud.githubusercontent.com/assets/128166/12302005/ea12cfa4-ba1a-11e5-8566-86975e266b3b.png)

**Comment by Neftas** [comment] 2016-01-13 20:38
Yes, this is done because the syntax `[text](text)` is a link in Markdown, and spaces in the part between the parentheses would otherwise break images in Anki when Markdown is toggled. Obviously this is not what you would want here. I will take a look at it.

**Comment by Neftas** [comment] 2016-01-23 18:13
Should be fixed in 91c9125f1aa939ce8857b3c798e2eacbaa8c2860. This is **not** yet on AnkiWeb, because I want to tackle some other issues first. But if you want, you can download the code from here and see if this fixes your problems with spaces in code blocks.

**Comment by AGBrown** [comment] 2016-01-23 19:12
Awesome, thank you, if I have time I'll grab the code and test it.

**Comment by AGBrown** [comment] 2016-02-01 19:38
@Neftas - To test this, do I just drop the `extra_buttons` folder and `Supplementary Buttons Anki.py` files into the `addons` directory, or is there more to it than that?

**Comment by Neftas** [comment] 2016-02-01 20:13
@AGBrown Thanks for taking the time to test. I have not yet released a new version to AnkiWeb -- there were unrelated problems on Windows that forced me to refactor a lot of code (the timestamp on AnkiWeb indicated that I uploaded the new version and then pulled it again, because it threw errors on Windows). But it seems like I fixed those problems, so I will probably put the new release up tomorrow. It is probably easiest for you to just grab the new release from AnkiWeb when I put it there. I will let you know here when I've done so.

**Comment by Neftas** [comment] 2016-02-02 18:56
I've put the fixes on AnkiWeb. Could you let me know if this fixes your issues?

**Comment by AGBrown** [comment] 2016-02-07 21:03
@Neftas. The test case now renders correctly, and reverts to the original markdown text when switching off markdown mode.

As an aside, it does still ask to cancel/replace/overwrite - is that expected?

**Comment by Neftas** [comment] 2016-02-08 05:42
@AGBrown It will show the popup whenever the Markdown syntax you entered is not equal to the Markdown it would generate from the current card (the displayed result). I'm using `html2text` to check this, and sometimes the Markdown generated by it is (slightly) different from the Markdown you entered, especially if you use "complex" syntax (tables, footnotes, etc.). If this bothers you, you can disable the popup by ticking the appropriate checkbox in the options. It will then always choose `Replace`, which is what you want most of the time, as it will simply restore the Markdown you originally entered.

**Comment by Neftas** [comment] 2016-02-08 05:55
I just noted that the issue is solved for fenced code blocks, but persists for code blocks that were created by indenting four spaces.

**Comment by AGBrown** [comment] 2016-02-08 07:58
That makes sense, thanks.

**Comment by AGBrown** [comment] 2016-02-08 07:59
Interesting. I must only be using fenced and inline blocks.

**Comment by Neftas** [comment] 2017-01-25 18:54
Better late than never,  0303b95 fixes this issue when you indent by four spaces.

**Closed** 2017-04-18 18:04 UTC
Labels: bug
