### ISSUE TITLE
Error on Windows when username contains non-ASCII characters

### ISSUE THREAD

**Issue by MuggleYeung** [Neftas/supplementary-buttons-anki#60] opened 2016-01-09 07:07 UTC
Hi, after I installed this plug in, I got the following error when I re-opened anki:
-------------------------
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.addons", line 41, in loadAddons
  File "c:\pyi\iu.py", line 436, in importHook
  File "c:\pyi\iu.py", line 521, in doimport
  File "C:\Users\־��\Documents\Anki\addons\Supplementary Buttons Anki.py", line 2, in <module>
    import extra_buttons.extra_buttons
  File "c:\pyi\iu.py", line 436, in importHook
  File "c:\pyi\iu.py", line 521, in doimport
  File "C:\Users\־��\Documents\Anki\addons\extra_buttons\extra_buttons.py", line 36, in <module>
    from utility import Utility
  File "c:\pyi\iu.py", line 436, in importHook
  File "c:\pyi\iu.py", line 521, in doimport
  File "C:\Users\־��\Documents\Anki\addons\extra_buttons\utility.py", line 37, in <module>
    from markdown.extensions.fenced_code import FencedCodeExtension
  File "c:\pyi\iu.py", line 436, in importHook
  File "c:\pyi\iu.py", line 521, in doimport
  File "C:\Users\־��\Documents\Anki\addons\extra_buttons\markdown\extensions\fenced_code.py", line 22, in <module>
    from .codehilite import CodeHilite, CodeHiliteExtension, parse_hl_lines
  File "c:\pyi\iu.py", line 436, in importHook
  File "c:\pyi\iu.py", line 521, in doimport
  File "C:\Users\־��\Documents\Anki\addons\extra_buttons\markdown\extensions\codehilite.py", line 28, in <module>
    if package.endswith("addons"):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd6 in position 9: ordinal not in range(128)

I'm running Anki on Surface 3 Windows 10.

Also under Tools>Addons this plugin is listed as "Supplementary Buttons Anki" rather than "Power format pack"

If anyone knows what is going on, I'd appreciate the help.

Muggle

**Comment by Neftas** [comment] 2016-01-09 19:47
From the error you posted it looks like you have a username (`C:\Users\<your_name>`) that is not properly understood because of your system's encoding. Windows unfortunately has these kind of problems where non-ASCII paths tend to cause errors. So as not to force you to create another user or changing OSes (I recommend Linux ;-), I have made a change to the code and posted it on AnkiWeb. Could you reinstall the addon (delete the `extra_buttons` folder in your `Documents\Anki\addons` folder as well) and tell me if the error disappears? Thanks!

**Comment by CoffeeDrinkRabbit** [comment] 2016-01-13 09:48
hi！The error still exist。。。。

**Comment by CoffeeDrinkRabbit** [comment] 2016-01-13 09:51
I really like your add but how can I deal with the problem。

**Comment by MuggleYeung** [comment] 2016-01-13 13:58
Hi, @Neftas

Thank you so much for helping me fix the error.

I’ve tried to reinstall the plug in (according to your steps -- delete the extra_buttons folder in your Documents\Anki\addons folder as well), but the error still exists.

-----Here's the error log-----

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons
Traceback (most recent call last):
File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.addons", line 41, in loadAddons
File "c:\pyi\iu.py", line 436, in importHook
File "c:\pyi\iu.py", line 521, in doimport
File "C:\Users\־��\Documents\Anki\addons\Supplementary Buttons Anki.py", line 2, in <module>
import extra_buttons.extra_buttons
File "c:\pyi\iu.py", line 436, in importHook
File "c:\pyi\iu.py", line 521, in doimport
File "C:\Users\־��\Documents\Anki\addons\extra_buttons\extra_buttons.py", line 33, in <module>
from utility import Utility
File "c:\pyi\iu.py", line 436, in importHook
File "c:\pyi\iu.py", line 521, in doimport
File "C:\Users\־��\Documents\Anki\addons\extra_buttons\utility.py", line 37, in <module>
from markdown.extensions.fenced_code import FencedCodeExtension
File "c:\pyi\iu.py", line 436, in importHook
File "c:\pyi\iu.py", line 521, in doimport
File "C:\Users\־��\Documents\Anki\addons\extra_buttons\markdown\extensions\fenced_code.py", line 22, in <module>
from .codehilite import CodeHilite, CodeHiliteExtension, parse_hl_lines
File "c:\pyi\iu.py", line 436, in importHook
File "c:\pyi\iu.py", line 521, in doimport
File "C:\Users\־��\Documents\Anki\addons\extra_buttons\markdown\extensions\codehilite.py", line 36, in <module>
package = unicode(package, "utf8")
File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/encodings.utf_8", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xbb in position 11: invalid start byte

Muggle

**Comment by gunnarmaluf** [comment] 2016-02-04 10:48
I believe there's a work around.
In my case the path is: D:\N�o Apagar\Documents\Anki\addons\extra_buttons\
So there's a "ã" that is causing the problem. If anki could give us a way to select another folder for it's addons (ie: c:\anki\addons) then I believe it would fix the issue.

I will try it later at home and let you guys know.

If there's a way for you to decode the path choosing the correct codec inside the code would be the best

Might help taking a look at 
codecs.getencoder(encoding)
Look up the codec for the given encoding and return its encoder function
https://docs.python.org/2/library/codecs.html

If I understood correctly you would pass the path to the getencoder() and it would return the name of the correct codec.

Hope it helps.

**Comment by gunnarmaluf** [comment] 2016-02-04 21:00
Hi
I got home now and  renamed my folder from
"D:\N�o Apagar\" to D:\Nao Apagar\  
(ã to a) 

And now the addon is working!

**Comment by Neftas** [comment] 2016-02-05 06:00
@gunnarmaluf  great that you've got it working. Unfortunately, as stated above, I cannot ask everybody to only use the English alphabet in their user names.

Meanwhile, on Windows 10, I created a user `петя` so that I could test this issue. But I cannot even open Anki because it will throw an error right away (`WindowsError: [123]`). How did you guys even got Anki working in the first place, seeing that it doesn't like non-English (non-ASCII) characters?

**Comment by gunnarmaluf** [comment] 2016-02-05 15:49
@Neftas I use Windows 7 and my username does not have any non english characters. 
I got the message only after installing the addon, not before. Pure anki worked fine. Maybe that
windows error is specific for Windows 10? Have you tried changing the region and language settings to see if it helps?

**Comment by gunnarmaluf** [comment] 2016-02-05 15:56
Another easy workaround is to select a different Documents folder in windows. Right click the documents folder, and select another folder in a path out of your username folder. Doing this will enable anki to install the addon in a folder that would not cause problems and you will be able to keep your username.

**Comment by Neftas** [comment] 2016-02-05 20:09
Issue is fixed in fe8ed7a568ba96ebf475a93b4b2d8253e42d7cc5. You can update the addon from AnkiWeb.

**Comment by Neftas** [comment] 2016-02-05 20:10
@gunnarmaluf Thanks for the helpful comments. You were right that I needed to change the region & language settings. I could then reproduce the error reported here and fix it. Thanks again for reporting, and I hope you will find the addon useful.

**Closed** 2016-05-31 19:31 UTC
Labels: bug
